### ISSUE TITLE
89th Amateur Series Division 7 underway with live web based broadcast

### ISSUE THREAD

**Issue by GrahamCCRL** [jtheardw/mantissa#1]
89TH AMATEUR SERIES (Division 7)

Intel i7 Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
IECGMasters.cgb book
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 44 rounds
All engines 64-bit where available

The top engine will be promoted and the bottom engine will be relegated. Any other changes of division will be at my discretion and may not necessarily involve playoff matches.

Participants

Mantissa 2.5.0 64-bit
Drosophila 1.6 64-bit
Supernova 2.4 64-bit
MadChess 3.0 64-bit
KnightX 3.1 64-bit
Lozza 2.0 64-bit
Betsabe II 2020
Raven 1.20 64-bit
RookieMonster 1.9.4 64-bit
Myrddin 0.88 64-bit
paulchen332 0.1.1 64-bit
CT800 1.43 64-bit

Games and standings will be available after every six rounds from the following link:
http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=13504

Web based link for live viewing (huge thanks to Jay - Berserk author).
http://tlcv.net/16094

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your computer, you can watch the games live move by move. You'll also be able to chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959
Host - GrahamCCRL.dyndns.org Port - 16094

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by jtheardw** [comment]
Thanks for sending these heads up. Looking forward to 90th division!

**Comment by GrahamCCRL** [comment]
Me too! :-)

I'll eventually run a gauntlet for Mantissa, but there is quite a long list
at present.

Graham.

**Comment by GrahamCCRL** [comment]
Go US/Canada!

:-)

________________________________
From: Graham Banks ***@***.***>
Sent: Monday, May 9, 2022 6:04 AM
To: Mark L. ***@***.***>; Larry Kaufman ***@***.***>; Jay Honnold ***@***.***>; Andrew Grant ***@***.***>; ***@***.*** ***@***.***>; Jon Dart ***@***.***>; ***@***.*** ***@***.***>; jtheardw/mantissa ***@***.***>; Erin Dame ***@***.***>; Mike Yang ***@***.***>; John Merlino ***@***.***>; ***@***.*** ***@***.***>; fab10 ***@***.***>; Andreas Matthies ***@***.***>; Ronald Friederich ***@***.***>; Volodymyr Shcherbyna ***@***.***>; Ed Schroder ***@***.***>; Vadim Chizhov ***@***.***>; Alex Brunetti ***@***.***>
Subject: US/Canada Selection v World Selection

US/CANADA Selection v WORLD Selection

Intel i7-4770k Quad
ChessGUI
256mb hash each where possible
3-4-5 piece tablebases
Ponder off
GBSelect2021.cgb book
40 moves in 16 minutes repeating (adapted for the CCRL)
Engines on each board will play a 12 game match
All engines 1CPU


MATCHES (updated as able)

(0.0-0.0) Dragon 3 by Komodo 64-bit v Stockfish 15 64-bit
(0.0-0.0) Berserk 8.5.1 64-bit v Koivisto 8.0 2.2 64-bit
(0.0-0.0) Ethereal 13.50 64-bit v Revenge 2.0 64-bit
(0.0-0.0) SlowChess Blitz 2.8 64-bit v RubiChess 20220223 64-bit
(0.0-0.0) Seer 2.5.0 64-bit v RofChade 2.321 64-bit
(0.0-0.0) Arasan 23.3 64-bit v Igel 3.0.5 64-bit
(0.0-0.0) Wasp 5.50 64-bit v Rebel 15 64-bit
(0.0-0.0) Zahak 9.0 64-bit v Velvet 3.3.0 64-bit
(0.0-0.0) Mantissa 3.3.0 64-bit v Counter 4.0 64-bit
(0.0-0.0) Weiawaga 5.0 64-bit v Protej 0.6.2 64-bit
(0.0-0.0) RookieMonster 1.9.8 64-bit v K2 0.99
(0.0-0.0) Supernova 2.4 64-bit v Inanis 1.0.1 64-bit
(0.0-0.0) Myrddin 0.88 64-bit v Leorik 2.0 64-bit


Current score (based on board matches)

0.0 - US/CANADA
0.0 - WORLD


Live broadcast here:
https://tlcv.net/16093<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftlcv.net%2F16093&data=05%7C01%7C%7C71734a0f490b48de3ad408da31a33241%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637876874233124533%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JqT56EfSYFKROO9clzfYSR1igg%2Bjq%2BW1MAaleCWy%2F%2FQ%3D&reserved=0>

**Comment by GrahamCCRL** [comment]
*94TH AMATEUR SERIES (Division 3)*

Intel i7 Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
Top15-2022.cgb book (limited to 8 moves depth)
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 44 rounds
All engines 64-bit 1CPU (where available)

*The top engine will gain automatic promotion and the bottom engine will
gain automatic relegation. Any other changes of division will be at my
discretion and may not necessarily involve playoff matches.*



*Participants*

Uralochka 3.53a 64-bit (new)
Danasah 9.00 64-bit (relegated)
Black Marlin 5.0 64-bit
LG Evolution NN 3.15.4 64-bit
Expositor 2WN29 64-bit (promoted)
Dark Toga 1.1 64-bit (relegated)
Halogen 10 64-bit
Roc 1.8 64-bit
Nirvanachess 2.5 64-bit
Drofa 3.3.0 64-bit
Mantissa 3.3.0 64-bit (promoted)
FabChess 1.16 64-bit (promoted)


Games and standings will be available after every six rounds from the
following link:
http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=14245

Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16092

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959
Host - GrahamCCRL.dyndns.org Port - 16092

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*95TH AMATEUR SERIES (Division 4)*

Intel i7 Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
ICCF-Pre2022HQ.cgb book (limited to 8 moves)
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 44 rounds
All engines 64-bit 1CPU (where available)

*The top engine will gain automatic promotion and the bottom engine will
gain automatic relegation. Any other changes of division will be at my
discretion and may not necessarily involve playoff matches.*



*Participants*

Orion 0.9 64-bit
Winter 0.9 64-bit
Counter 4.1 64-bit
Mantissa 3.3.0 64-bit (relegated)
Invictus r382 64-bit
SmallBrain 5.0 64-bit (promoted)
Mr Bob 1.1.0 64-bit
Bit-Genie 9.0 64-bit
Amoeba 3.4 64-bit
Topple 0.8.1 64-bit
Cheng 4.41 64-bit
FabChess 1.16 64-bit (relegated)


Games and standings will be available after every six rounds from the
following link:
http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=14384#p127991

Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16094

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959
Host - GrahamCCRL.dyndns.org Port - 16094

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*WINTER AND THE PERSECUTED*

Intel i7 Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
Top15-2022.cgb book
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 44 rounds
All engines 64-bit 1CPU (where available)


*Participants*

Halogen 10 64-bit
Roc 1.8 64-bit
Winter 0.9 64-bit
Drofa 3.3.0 64-bit
NirvanaChess 2.5 64-bit
Counter 4.1 64-bit
Vajolet2 2.8 64-bit
Mantissa 3.3.0 64-bit
Rybka 4.1 64-bit
Mr Bob 1.1.0 64-bit
Bit-Genie 9 64-bit
iCE 4.0 64-bit


Games and standings will be available after every four rounds from the
following link:
http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=14486

Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16091

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959
Host - GrahamCCRL.dyndns.org Port - 16091

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*96TH AMATEUR SERIES (Division 3)*

Intel i7 Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
ChessOK-Pre2022HQ.cgb book (limited to 8 moves depth)
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 44 rounds
All engines 64-bit 1CPU (where available)

*The top engine will gain automatic promotion and the bottom engine will
gain automatic relegation. Any other changes of division will be at my
discretion and may not necessarily involve playoff matches.*



*Participants*

Marvin 6.0.0 64-bit (relegated)
Weiss 2.0 64-bit (relegated)
Combusken 2.0.0 64-bit
Stash 33.0 64-bit (relegated)
Mantissa 3.7.2 64-bit (promoted)
Danasah 9.00 64-bit
LG Evolution NN 3.15.4 64-bit
Dark Toga 1.1 64-bit
Halogen 10 64-bit
Expositor 2WN29 64-bit
Alexandria 2.4 64-bit (promoted)
Drofa 3.3.0 64-bit


Games and standings will be available after every six rounds from the
following link:
http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=14548

Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16092

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959
Host - GrahamCCRL.dyndns.org Port - 16092

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*THE CURSE OF NEMORINO*

Intel i7-4770k
ChessGUI
256mb hash each where possible
3-4-5 piece tablebases
Ponder off
FOEBOSv20.1.cgb book (restricted to 8 moves depth)
40 moves in 16 minutes repeating
10 cycles 70 rounds
All engines 1CPU (64-bit where available)


*Participants*

Nemorino 6.05 64-bit
Caissa 1.0 64-bit
Marvin 6.0.0 64-bit
Mantissa 3.7.2 64-bit
Zahak 10.0 64-bit
Weiss 2.0 64-bit
Hiarcs 15.0 64-bit
Shredder 13 64-bit

Games and standings will be available after every seven rounds from the
following link:
http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=14622

Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16094

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959
Host - GrahamCCRL.dyndns.org Port - 16094

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*US/CANADA Selection v WORLD Selection*

Intel i7-4770k Quad
ChessGUI
256mb hash each where possible
3-4-5 piece tablebases
Ponder off
GBSelect2021.cgb book
40 moves in 16 minutes repeating (adapted for the CCRL)
Engines on each board will play a 12 game match
All engines 1CPU


*MATCHES* *(updated as able)*

*(0.0-0.0)* Dragon 3 by Komodo 64-bit v Stockfish 15 64-bit
*(0.0-0.0)* Berserk 8.5.1 64-bit v Koivisto 8.0 2.2 64-bit
*(0.0-0.0)* Ethereal 13.50 64-bit v Revenge 2.0 64-bit
*(0.0-0.0)* SlowChess Blitz 2.8 64-bit v RubiChess 20220223 64-bit
*(0.0-0.0)* Seer 2.5.0 64-bit v RofChade 2.321 64-bit
*(0.0-0.0)* Arasan 23.3 64-bit v Igel 3.0.5 64-bit
*(0.0-0.0)* Wasp 5.50 64-bit v Rebel 15 64-bit
*(0.0-0.0)* Zahak 9.0 64-bit v Velvet 3.3.0 64-bit
*(0.0-0.0)* Mantissa 3.3.0 64-bit v Counter 4.0 64-bit
*(0.0-0.0)* Weiawaga 5.0 64-bit v Protej 0.6.2 64-bit
*(0.0-0.0)* RookieMonster 1.9.8 64-bit v K2 0.99
*(0.0-0.0)* Supernova 2.4 64-bit v Inanis 1.0.1 64-bit
*(0.0-0.0)* Myrddin 0.88 64-bit v Leorik 2.0 64-bit


Current score (based on board matches)

*0.0 - US/CANADA*
*0.0 - WORLD*


Live broadcast here:
https://tlcv.net/16093

**Comment by GrahamCCRL** [comment]
*SUMMIT OF THE ROC NEST*

Intel i7 Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
ChessOK-Pre2022HQ.cgb book
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 44 rounds
All engines 64-bit 1CPU (where available)


*Participants*

Halogen 10 64-bit
Expositor 2WN29 64-bit
Roc 1.8 64-bit
Orion 0.9 64-bit
Winter 0.9 64-bit
NirvanaChess 2.5 64-bit
Drofa 3.3.0 64-bit
Vajolet2 2.8 64-bit
Mantissa 3.3.0 64-bit
Counter 4.1 64-bit
Mr Bob 1.1.0 64-bit
Texel 1.07 64-bit 64-bit


Games and standings will be available after every six rounds from the
following link:
http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=14307

Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16092

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959
Host - GrahamCCRL.dyndns.org Port - 16092

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*97TH AMATEUR SERIES (Division 2)*

Intel i7 Quad
ChessGUI
256mb hash each where possible
3-4-5 piece tablebases
Ponder off
ICCF-Pre2022HQ.cgb book (limited to 8 moves depth)
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 44 rounds
All engines 1CPU (64-bit where available)

*The top engine will gain automatic promotion and the bottom engine will
face automatic relegation. Any other changes of division will be at my
discretion and may not necessarily involve playoff matches.*



*Participants*

Uralochka 3.38c 64-bit
Black Marlin 7.0 64-bit
Wasp 6.00 64-bit
Devre 4.0 64-bit (relegated)
Fire 8.3 64-bit (relegated)
Marvin 6.1.0 64-bit (promoted)
Booot 7.0 64-bit
Nemorino 6.05 64-bit
Clover 3.1 64-bit
Tucano 10.0 64-bit
Velvet 4.1.0 64-bit
Mantissa 3.7.2 64-bit (promoted)


Games and standings will be available after every six rounds from the
following link:
http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=14702

Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16094

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959
Host - GrahamCCRL.dyndns.org Port - 16094

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*THE GODDESS IN THE VELVET ROBE*

Intel i7-4770k Quad
ChessGUI
256mb hash each where possible
3-4-5 piece tablebases
Ponder off
SuperGM2020.cgb book
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 44 rounds


*Participants*

Nemorino 6.05 64-bit
Caissa 1.4 64-bit
Booot 7.0 64-bit
Clover 3.1 64-bit
Tucano 10.00 64-bit
Velvet 4.1.0 64-bit
Xiphos 0.6 64-bit
Counter 5.0 64-bit
Mantissa 3.7.2 64-bit
Zahak 10.0 64-bit
SmallBrain 6.0 64-bit
Expositor 2BR17 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16091

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959
Host - GrahamCCRL.dyndns.org Port - 16091

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*98TH AMATEUR SERIES (Division 3)*

Intel i7 Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
HarryScnapp.cgb book (limited to 8 moves depth)
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 44 rounds
All engines 64-bit 1CPU (where available)

*The top engine will gain automatic promotion and the bottom engine will
gain automatic relegation. Any other changes of division will be at my
discretion and may not necessarily involve playoff matches.*

*Participants*

Mantissa 3.7.2 64-bit (relegated)
Counter 5.0 64-bit (promoted)
Zahak 10.0 64-bit
SmallBrain 6.0 64-bit
Weiss 2.0 64-bit
Stash 34.0 64-bit
Expositor 2BR17 64-bit
Alexandria 3.1.0 64-bit
Combusken 2.0.0 64-bit
StockNemo 5.7.0.0 64-bit (promoted)
Danasah 9.00 64-bit
LG Evolution NN 3.15.4 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16092

**Comment by GrahamCCRL** [comment]
*99TH AMATEUR SERIES (Division 4)*

Intel i7 Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
WorldClass2013-1.cgb book (limited to 8 moves)
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 44 rounds
All engines 64-bit 1CPU (where available)

*The top engine will gain automatic promotion and the bottom engine will
gain automatic relegation. Any other changes of division will be at my
discretion and may not necessarily involve playoff matches.*

*Participants*

Mantissa 3.7.2 64-bit (relegated)
Weiss 2.0 64-bit (relegated)
Combusken 2.0.0 64-bit (relegated)
Drofa 3.3.22 64-bit
Alexandria 3.1.0 64-bit (relegated)
RukChess 3.0.12 64-bit
Orion 0.9 64-bit
Demolito 2021-10-04 64-bit
Roc 1.9.1 64-bit
Avalanche 1.3.1 64-bit (promoted)
Invictus r382 64-bit (06-2021)
Sturddle 1.04 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16093

**Comment by GrahamCCRL** [comment]
*TAKING STOCK ON A FROZEN NIGHT*

Intel i7-4770k Quad
ChessGUI
256mb hash each where possible
3-4-5 piece tablebases
Ponder off
Top10SuperGM2020.cgb book
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 36 rounds


*Participants*

Counter 5.0 64-bit
Mantissa 3.7.2 64-bit
LG Evolution 3.16 64-bit
Zahak 10.0 64-bit
Pawn 1.0 64-bit
Frozenight 6.0.0 64-bit
Stash 34.0 64-bit
Expositor 2BR17 64-bit
Weiss 2.0 64-bit
StockNemo 5.7.0.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16093
