### ISSUE TITLE
AVX

### ISSUE THREAD

**Issue by AlexBrunetti** [jtheardw/mantissa#2]
It doesn't run on my AVX machine. Are you sure it's AVX and not AVX2?

Alex

**Comment by jtheardw** [comment]
Good catch.  I've updated the binaries in the release and the build scripts to not require AVX2.  Can you try again and let me kow if it works now?

**Comment by AlexBrunetti** [comment]
It works fine, testing started!

Thanx,
Alex

**Comment by jtheardw** [comment]
Awesome!  Thank you!
